// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"user_id"`
	WorkName   pgtype.Text      `json:"work_name"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	PlannedEnd pgtype.Timestamp `json:"planned_end"`
	ActualEnd  pgtype.Timestamp `json:"actual_end"`
	IconID     pgtype.Int4      `json:"icon_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Tier      int32            `json:"tier"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
