// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CompleteSession(ctx context.Context, arg CompleteSessionParams) (Session, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindActiveSessionByUserID(ctx context.Context, userID int32) (Session, error)
	FindSessionByID(ctx context.Context, id int32) (Session, error)
	FindUserByID(ctx context.Context, id int32) (User, error)
	FindUserByName(ctx context.Context, name string) (User, error)
	FindUserByNameForUpdate(ctx context.Context, name string) (User, error)
	GetActiveSessions(ctx context.Context) ([]GetActiveSessionsRow, error)
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]Session, error)
	UpdateSessionPlannedEnd(ctx context.Context, arg UpdateSessionPlannedEndParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
