version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: workspace-dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: workspace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  work-tracker:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: workspace-dev-tracker
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/workspace?sslmode=disable
      PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data:
