name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Go mod cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -v

      # Docker ビルドは必要に応じて有効化
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build (no push)
        run: |
          docker build -f infrastructure/Dockerfile -t work-tracker:ci .
